version: '3.8'


services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis/data/redis:/data
    command: redis-server --appendonly yes

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}


