version: '3.8'


services:
  postgres:
    image: postgres:14-alpine
    networks:
      - moj_network
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

  db_writer:
    networks:
      - moj_network
    volumes:
      - ./volumes/models:/app/models
    healthcheck:
      test: "netstat -ltn | grep -c 5000"
    ports:
      - "5005:5000"
    build:
      dockerfile: ./db_writer/Dockerfile
    depends_on:
      - postgres

  redis:
    image: "redis:latest"
    networks:
      - moj_network
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis/data/redis:/data
    command: redis-server --appendonly yes
    depends_on:
      - db_writer



networks:
  moj_network:
    driver: bridge