version: '3.8'

services:
  ngrok:
    image: ngrok/ngrok:latest
    networks:
      - moj_network
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    volumes:
      - ./ngrok.yml:/etc/ngrok.yml


networks:
  moj_network:
    external: true
    name: databases_moj_network